### ISSUE TITLE
NullPointerException - Calendar.getInstance()

### ISSUE THREAD

**Issue by danielross** [keenlabs/KeenClient-Java#63]
Hi,

I received a crash report that seems to indicate that the `Calendar.getInstance()` call was unable to initialise. Have you encountered this problem before? Does `Calendar.getInstance()` not work for every device? It looks like this device was a Huawei.

Thanks

```
java.lang.ExceptionInInitializerError
	at io.keen.client.java.KeenClient$Builder.buildInstance(Unknown Source)
	at io.keen.client.java.KeenClient$Builder.build(Unknown Source)
	...
Caused by: java.lang.NullPointerException
	at java.util.Calendar.getHwFirstDayOfWeek(Calendar.java:1608)
	at java.util.Calendar.setFirstDayOfWeekEx(Calendar.java:1573)
	at java.util.Calendar.<init>(Calendar.java:746)
	at java.util.GregorianCalendar.<init>(GregorianCalendar.java:338)
	at java.util.GregorianCalendar.<init>(GregorianCalendar.java:314)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:378)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:368)
	at io.keen.client.java.KeenClient.<clinit>(Unknown Source)
	... 18 more
```

**Comment by Geeber** [comment]
Hi Daniel, sorry for the delayed reply (I've been out on vacation the past few weeks). I haven't seen this before but it's certainly plausible that some particular device has an issue here; either a manufacturer bundled the software in some strange way, or even a single specific user rooted and modified their device in a custom (but broken) way. Oh the joys of Android fragmentation.

For what it's worth though, I don't see any method named `getHwFirstDayOfWeek` in the android source code:

https://android.googlesource.com/platform/libcore.git/+/android-5.1.1_r24/luni/src/main/java/java/util/Calendar.java
https://android.googlesource.com/platform/libcore.git/+/android-4.4_r1/luni/src/main/java/java/util/Calendar.java
https://android.googlesource.com/platform/libcore.git/+/android-3.2.4_r1/luni/src/main/java/java/util/Calendar.java

So that makes me suspect that this crash is not from stock code.

I'm not really sure that there's much intelligent we can do in this case. If we can't initialize a `SimpleDateFormat` for ISO-8601, we'd have to fall back to replicating the behavior in some other way. I doubt that's going to be worth the added code complexity, unless we can find evidence that this issue is widespread.

What we might be able to do, however, is at least isolate it so that the Keen SDK will fail to work but do so silently (rather than throing an `ExceptionInInitializationError`). Does that sound reasonable to you?

**Comment by danielross** [comment]
Hi Kevin,

Thanks for your reply, it follows my own line of reasoning. I don't think it is worth the hassle to do something overly complicated for this very specific case.
On our side we chose to go along with catching the error silently, so that sounds reasonable to me.
