### ISSUE TITLE
QueryResult.execute() doesn't return ordered values

### ISSUE THREAD

**Issue by alejandro-du** [keenlabs/KeenClient-Java#76]
When QueryResult.execute() returns a Map, its entries are not ordered. That's a problem when using the returned data to create a chart for example. Ideally, the method should return an ordered map. In the case of IntervalResults, I think this can be easily fixed by using a TreeMap instead of a HashMap [here](https://github.com/keenlabs/KeenClient-Java/blob/master/query/src/main/java/io/keen/client/java/KeenQueryClient.java#L317), and implementing a Comparator.

**Comment by dkador** [comment]
Thanks for the issue report. I want to make sure I understand exactly the problem you're seeing (I think I do, but let's be sure).

`KeenQueryClient.execute()` returns a `QueryResult` object. There's no explicit problem here. For intervals, you'd call `.getIntervalResults` on the returned `QueryResult` object. This is where the problem is. It returns a `Map<AbsoluteTimeframe, QueryResult>` which, as you say, is unordered. That's no good. We could fix that by making it a sorted Map, as you suggest. Or we could treat it like the API treats it, which is as a List of Maps.

Can you confirm that either fix would resolve what you're seeing? Or is there a more general problem here?

**Comment by alejandro-du** [comment]
Exactly. Both fixes would solve the problem.

**Comment by dkador** [comment]
Great. Thanks for confirming.
